const globalActionConstants = {
    STUDENT_INFO_LOADING: "STUDENT_INFO_LOADING",
    STUDENT_INFO_RECEIVED: "STUDENT_INFO_RECEIVED",

    TEACHER_INFO_LOADING: "TEACHER_INFO_LOADING",
    TEACHER_INFO_RECEIVED: "TEACHER_INFO_RECEIVED",

    VISITS_INFO_LOADING: "VISIT_INFO_LOADING",
    VISITS_INFO_RECEIVED: "VISIT_INFO_RECEIVED",

    CREATE_VISIT_LOADING: "CREATE_VISIT_LOADING",
    CREATE_VISIT_SECCESS: "CREATE_VISIT_SECCESS",
    CREATE_VISIT_ERROR: "CREATE_VISIT_ERROR"

}

export default globalActionConstants;