const userActionConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_FINISHED: 'USERS_LOGIN_FINISHED',

    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
    CURRENT_USER_INFO_SUCCESS: 'CURRENT_USER_INFO_SUCCESS',
    USER_INFO_ERROR: 'USER_INFO_ERROR',
    CLEAR_STATE: 'CLEAR_STATE',

    LOGIN_FINISHED: 'LOGIN_FINISHED',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
};

export default userActionConstants;
